# Generated by Django 6.0.2 on 2026-07-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="source",
            field=models.CharField(default="manual", max_length=60),
        ),
    ]
