# Generated by Django 6.0.2 on 2026-07-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_alter_task_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
